spring:
  application:
    name: siggi-ci-keys
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    database: POSTGRESQL

management:
  port: 9090

siggi:
  deploykeys:
    size: 1024
    comment: "testing"
